#!/bin/bash
# unquote
# Author: Lucas Vitalos
# Date: 2017-04-27
# Platform: Amazon Linux AMI release 2017.03;
#           GNU bash, version 4.2.46(1)-release 
#           (x86_64-redhat-linux-gnu)
# Unquotes lists in a csv file
# Usage: unquote CSVFILE

if [[ $# < 1 ]] ; then
    echo "This program requires the name of a CSV file as input"
    exit 1
fi

if [[ ! -f "$1" ]] ; then
    echo "Could not find specified file; please check the name"
    echo "and path to the file and try again."
    exit 2
fi

cat "$1" | tr -d '"' >> "$1.tmp"

rm -f "$1"

mv "$1.tmp" "$1"

exit 0
